---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script:
- bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test FUTURE_PARSER=yes
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test FUTURE_PARSER=yes
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.4
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.4
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=rubocop
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  allow_failures:
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
notifications:
  email: false
deploy:
  provider: puppetforge
  user: dhoppe
  password:
    secure: "rxlXRtuj2l/aYIpX0FGZONIMubzwdh7TB9CZuDKv55RD15vClOwu618PlI6EsbljcMjHZyT6RpavW4e/loL8rdg0vwXbCFZasSyb34RIDmcXLDZlYHpNzQ9FlQo73dlx1GhLyW6cuMGL4p765rnpgPxTmyoQ950ekwZAgPYwHKM="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
